Update Ghost 4 SMTP configuration setup
bitnami/bitnami-docker-ghost pull request #113
Opened 2021-07-12 11:55 UTC by megawebmaster

**Description of the change**

Update Ghost setup script to properly set SMTP mailer settings for Ghost 4.

**Benefits**

User can configure SMTP settings using env variables (as one would expect).

**Possible drawbacks**

None.

**Applicable issues**

No issues - just a PR to fix the problem.

2021-07-13 07:39 UTC, javsalgar requested changes
Thank you so much for the PR! Changes requested

2021-07-13 07:39 UTC, javsalgar commented on 4/debian-10/rootfs/opt/bitnami/scripts/libghost.sh
> +                ghost_conf_set "mail.from" "$GHOST_EMAIL"
Note that the same logic should apply to both Ghost 3 and 4. Does Ghost 3 also use the `mail.` prefix instead of `smtpConfig`? Also, could you add a comment with the link to the configuration settings?

2021-07-15 06:55 UTC, megawebmaster commented on 4/debian-10/rootfs/opt/bitnami/scripts/libghost.sh
> +                ghost_conf_set "mail.from" "$GHOST_EMAIL"
Done. I used only Ghost 4, but from the code for 3.x: yes, it does.

2021-07-16 07:43 UTC, javsalgar approved these changes
Awesome! Thanks!

2021-07-16 12:17 UTC, merged